replicaCount: 2

image:
  repository: integrator-project
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

env:
  NODE_ENV: production
  API_BASE_PATH: /api/v1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

