import fs from "node:fs";
import path from "node:path";
import {
  defineAdapterManifest,
  normalizeAdapterKey,
  toAdapterDisplayName,
  type AdapterManifest,
} from "@integration/shared";

export type CreateAdapterOptions = {
  name: string;
  adaptersRootDir?: string;
  force?: boolean;
};

export type CreateAdapterResult = {
  adapterKey: string;
  adapterDir: string;
  filesWritten: string[];
};

type ParsedArgs = {
  name: string;
  root?: string;
  force: boolean;
};

function parseArgumentValue(args: string[], flag: string): string | undefined {
  const index = args.indexOf(flag);
  if (index < 0) {
    return undefined;
  }
  return args[index + 1];
}

export function parseCreateAdapterArgs(args: string[]): ParsedArgs {
  const name = parseArgumentValue(args, "--name");
  if (!name) {
    throw new Error(
      "Missing required --name argument. Example: npm run create:adapter -w @integration/core -- --name my-adapter",
    );
  }
  const root = parseArgumentValue(args, "--root");
  const force = args.includes("--force");
  return {
    name,
    root,
    force,
  };
}

function resolveRepoRoot(): string {
  return path.resolve(__dirname, "../../../..");
}

function ensureDirectory(inputPath: string): void {
  if (!fs.existsSync(inputPath)) {
    fs.mkdirSync(inputPath, {
      recursive: true,
    });
  }
}

function normalizeDisplayName(baseDisplayName: string): string {
  const withoutSuffix = baseDisplayName.replace(/\s+adapter$/i, "").trim();
  const normalized = withoutSuffix || baseDisplayName;
  return `${normalized} Adapter`;
}

function normalizeAdapterClassName(baseDisplayName: string): string {
  const withoutSuffix = baseDisplayName.replace(/\s+adapter$/i, "").trim();
  const normalized = withoutSuffix || baseDisplayName;
  return `${normalized.replace(/\s+/g, "")}Adapter`;
}

function buildManifest(input: {
  adapterKey: string;
  adapterDisplayName: string;
  adapterClassName: string;
}): AdapterManifest {
  return defineAdapterManifest({
    schemaVersion: "1.0",
    key: input.adapterKey,
    displayName: input.adapterDisplayName,
    version: "0.1.0",
    description: `${input.adapterDisplayName} scaffold generated by create:adapter.`,
    entry: "./src/index.ts",
    exportName: input.adapterClassName,
    auth: {
      type: "none",
    },
    supportedTriggers: ["sample_trigger"],
    supportedActions: ["sample_action"],
    defaultEnabled: true,
    platform: {
      apiVersion: "v1",
      minCoreVersion: "1.0.0",
    },
  });
}

function buildPackageJson(input: {
  adapterKey: string;
}): Record<string, unknown> {
  return {
    name: `@integration/adapter-${input.adapterKey}`,
    version: "0.1.0",
    private: true,
    main: "src/index.ts",
    types: "src/index.ts",
    scripts: {
      build: "tsc -p tsconfig.json",
      lint: "tsc -p tsconfig.json --noEmit",
      test: "vitest run --passWithNoTests",
    },
    dependencies: {
      "@integration/shared": "*",
    },
  };
}

function buildTsConfig(): Record<string, unknown> {
  return {
    extends: "../../../tsconfig.base.json",
    compilerOptions: {
      rootDir: "src",
      outDir: "dist",
      composite: true,
    },
    include: ["src/**/*.ts"],
  };
}

function buildReadme(input: {
  adapterKey: string;
  adapterDisplayName: string;
}): string {
  return `# ${input.adapterDisplayName}

Generated by \`npm run create:adapter -w @integration/core -- --name ${input.adapterKey}\`.

## What To Implement Next

1. Replace placeholder auth handling in \`src/index.ts\`.
2. Replace sample trigger/action behavior with provider-specific logic.
3. Update \`manifest.json\` capabilities to match real trigger/action keys.
4. Add integration-focused tests for API calls and error mapping.
`;
}

function buildSourceTemplate(input: {
  adapterClassName: string;
  adapterKey: string;
  adapterDisplayName: string;
}): string {
  return `import {
  Adapter,
  AdapterActionResult,
  AdapterAuthResult,
  AdapterContext,
  AdapterTokenRefreshResult,
  AdapterTriggerResult,
  ActionDefinition,
  AdapterError,
  AuthPayload,
  TriggerDefinition,
  createAdapterLogger,
  createConfigValidator,
  defineAction,
  defineTrigger,
} from "@integration/shared";

type ${input.adapterClassName}Config = {
  baseUrl?: string;
};

export class ${input.adapterClassName} implements Adapter {
  readonly key = "${input.adapterKey}";
  readonly version = "0.1.0";

  private readonly logger = createAdapterLogger(this.key);
  private config: ${input.adapterClassName}Config = {};
  private readonly validate = createConfigValidator([
    (config) =>
      config.baseUrl === undefined || typeof config.baseUrl === "string"
        ? undefined
        : "baseUrl must be a string when provided.",
  ]);

  async init(config: Record<string, unknown>): Promise<void> {
    this.config = {
      baseUrl: typeof config.baseUrl === "string" ? config.baseUrl : undefined,
    };
    this.logger.info("adapter.init", {
      hasBaseUrl: Boolean(this.config.baseUrl),
    });
  }

  async authenticate(_payload: AuthPayload): Promise<AdapterAuthResult> {
    // TODO: Replace with provider-specific auth flow (OAuth/API key/etc).
    return {
      metadata: {
        mode: "none",
      },
    };
  }

  async listTriggers(): Promise<TriggerDefinition[]> {
    return [
      defineTrigger({
        key: "sample_trigger",
        name: "Sample Trigger",
        description: "Sample trigger placeholder for ${input.adapterDisplayName}.",
        inputSchema: {
          type: "object",
          properties: {
            payload: {
              type: "object",
            },
          },
          required: ["payload"],
        },
      }),
    ];
  }

  async listActions(): Promise<ActionDefinition[]> {
    return [
      defineAction({
        key: "sample_action",
        name: "Sample Action",
        description: "Sample action placeholder for ${input.adapterDisplayName}.",
        inputSchema: {
          type: "object",
          properties: {
            payload: {
              type: "object",
            },
          },
          required: ["payload"],
        },
      }),
    ];
  }

  async runTrigger(
    triggerKey: string,
    input: Record<string, unknown>,
    context: AdapterContext,
  ): Promise<AdapterTriggerResult> {
    if (triggerKey !== "sample_trigger") {
      throw new AdapterError(\`Unsupported trigger key "\${triggerKey}"\`, {
        code: "UNSUPPORTED_TRIGGER",
      });
    }

    this.logger.info("trigger.run", {
      triggerKey,
      workspaceId: context.workspaceId,
    });

    return {
      events: [
        {
          payload: input.payload || input,
          receivedAt: new Date().toISOString(),
        },
      ],
    };
  }

  async runAction(
    actionKey: string,
    input: Record<string, unknown>,
    context: AdapterContext,
  ): Promise<AdapterActionResult> {
    if (actionKey !== "sample_action") {
      throw new AdapterError(\`Unsupported action key "\${actionKey}"\`, {
        code: "UNSUPPORTED_ACTION",
      });
    }

    this.logger.info("action.run", {
      actionKey,
      workspaceId: context.workspaceId,
      hasRunId: Boolean(context.runId),
    });

    return {
      success: true,
      output: {
        acknowledged: true,
        payload: input.payload || input,
      },
    };
  }

  async validateConfig(config: Record<string, unknown>): Promise<{ valid: boolean; errors?: string[] }> {
    return this.validate(config);
  }

  async refreshToken(
    _currentCredentials: Record<string, unknown>,
    _context: AdapterContext,
  ): Promise<AdapterTokenRefreshResult> {
    throw new AdapterError("Token refresh is not implemented for this scaffold.", {
      code: "NOT_IMPLEMENTED",
      retryable: false,
    });
  }
}
`;
}

function buildTestTemplate(input: {
  adapterClassName: string;
}): string {
  return `import { describe, expect, it } from "vitest";
import { ${input.adapterClassName} } from "./index";

describe("${input.adapterClassName}", () => {
  it("exposes sample trigger and action definitions", async () => {
    const adapter = new ${input.adapterClassName}();
    await adapter.init({});
    const triggers = await adapter.listTriggers();
    const actions = await adapter.listActions();

    expect(triggers.map((trigger) => trigger.key)).toContain("sample_trigger");
    expect(actions.map((action) => action.key)).toContain("sample_action");
  });
});
`;
}

function writeJsonFile(filePath: string, value: unknown): void {
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function writeTextFile(filePath: string, value: string): void {
  fs.writeFileSync(filePath, value, "utf8");
}

export function scaffoldAdapter(
  options: CreateAdapterOptions,
): CreateAdapterResult {
  const adapterKey = normalizeAdapterKey(options.name);
  if (!adapterKey) {
    throw new Error("Adapter name produced an empty adapter key.");
  }

  const displayName = toAdapterDisplayName(adapterKey);
  const adapterDisplayName = normalizeDisplayName(displayName);
  const adapterClassName = normalizeAdapterClassName(displayName);
  const adaptersRootDir =
    options.adaptersRootDir || path.join(resolveRepoRoot(), "packages", "adapters");
  const adapterDir = path.join(adaptersRootDir, adapterKey);

  if (fs.existsSync(adapterDir)) {
    if (!options.force) {
      throw new Error(
        `Adapter directory already exists at "${adapterDir}". Use --force to overwrite.`,
      );
    }
    fs.rmSync(adapterDir, {
      recursive: true,
      force: true,
    });
  }

  ensureDirectory(adapterDir);
  ensureDirectory(path.join(adapterDir, "src"));

  const manifest = buildManifest({
    adapterKey,
    adapterDisplayName,
    adapterClassName,
  });
  const packageJson = buildPackageJson({
    adapterKey,
  });

  const filesWritten: string[] = [];
  const manifestPath = path.join(adapterDir, "manifest.json");
  writeJsonFile(manifestPath, manifest);
  filesWritten.push(manifestPath);

  const packageJsonPath = path.join(adapterDir, "package.json");
  writeJsonFile(packageJsonPath, packageJson);
  filesWritten.push(packageJsonPath);

  const tsConfigPath = path.join(adapterDir, "tsconfig.json");
  writeJsonFile(tsConfigPath, buildTsConfig());
  filesWritten.push(tsConfigPath);

  const readmePath = path.join(adapterDir, "README.md");
  writeTextFile(
    readmePath,
    buildReadme({
      adapterKey,
      adapterDisplayName,
    }),
  );
  filesWritten.push(readmePath);

  const sourcePath = path.join(adapterDir, "src", "index.ts");
  writeTextFile(
    sourcePath,
    buildSourceTemplate({
      adapterClassName,
      adapterKey,
      adapterDisplayName,
    }),
  );
  filesWritten.push(sourcePath);

  const testPath = path.join(adapterDir, "src", "index.test.ts");
  writeTextFile(
    testPath,
    buildTestTemplate({
      adapterClassName,
    }),
  );
  filesWritten.push(testPath);

  return {
    adapterKey,
    adapterDir,
    filesWritten,
  };
}

function main(): void {
  const parsed = parseCreateAdapterArgs(process.argv.slice(2));
  const result = scaffoldAdapter({
    name: parsed.name,
    adaptersRootDir: parsed.root,
    force: parsed.force,
  });

  console.log(`Created adapter scaffold: ${result.adapterKey}`);
  for (const filePath of result.filesWritten) {
    console.log(` - ${filePath}`);
  }
}

if (require.main === module) {
  try {
    main();
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error(`[create:adapter] ${message}`);
    process.exit(1);
  }
}
